package university.management.system;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


/* Java AWT Swing: Java AWT (Abstract Window Toolkit) and Swing are Java libraries used to
 build graphical user interfaces (GUI) for desktop applications. AWT provides the basic building
 blocks for GUI components, and Swing extends AWT with more advanced and customizable components.
 */

public class Project extends JFrame implements ActionListener
{

    /*
     JFrame is a class from the Swing library that represents a top-level window with a title bar and decorations.
    It is the foundation for creating graphical user interfaces (GUI) in Java applications. Developers use JFrame
    to create the main application window or a dialog box where they can add various Swing components such as
    buttons, labels, text fields, and more.

    ActionListener is an interface provided by the Swing library that is used to handle action events
    generated by components like buttons, menu items, and other interactive elements in a graphical user interface
    (GUI). When a user interacts with these components, an action event
    is triggered, and the ActionListener interface allows you to define what should happen in response to that event.

     */

    Project()
    {
        super("University Management System");
        setSize(1920, 1030);
        ImageIcon ic = new ImageIcon(getClass().getResource("/university/management/system/icons/photo.jpg"));
        Image i3 = ic.getImage().getScaledInstance(1900, 950, Image.SCALE_DEFAULT);
        ImageIcon icc3 = new ImageIcon(i3);
        JLabel l1 = new JLabel(icc3);

        add(l1);

        JMenuBar mb = new JMenuBar();

        JMenu master = new JMenu("Master");
        JMenuItem m1 = new JMenuItem("New Faculty");
        JMenuItem m2 = new JMenuItem("New Student Admission");
        master.setForeground(Color.BLUE);

        m1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon1.jpg"));
        Image image1 = icon1.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        m1.setIcon(new ImageIcon(image1));
        m1.setMnemonic('A');
        m1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, ActionEvent.CTRL_MASK));
        m1.setBackground(Color.WHITE);

        m2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/university/management/system/icons/addstu.png"));
        Image image2 = icon2.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        m2.setIcon(new ImageIcon(image2));
        m2.setMnemonic('B');
        m2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_M, ActionEvent.CTRL_MASK));
        m2.setBackground(Color.WHITE);

        m1.addActionListener(this);
        m2.addActionListener(this);


        JMenu user = new JMenu("Details");
        JMenuItem u1 = new JMenuItem("Student Details");
        JMenuItem u2 = new JMenuItem("Teacher Details");
        user.setForeground(Color.RED);

        u1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon4 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon3.png"));
        Image image4 = icon4.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        u1.setIcon(new ImageIcon(image4));
        u1.setMnemonic('C');
        u1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_D, ActionEvent.CTRL_MASK));
        u1.setBackground(Color.WHITE);

        u2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon5 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon4.jpg"));
        Image image5 = icon5.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        u2.setIcon(new ImageIcon(image5));
        u2.setMnemonic('D');
        u2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E, ActionEvent.CTRL_MASK));
        u2.setBackground(Color.WHITE);

        u1.addActionListener(this);
        u2.addActionListener(this);


        JMenu attendance = new JMenu("Attendance");
        JMenuItem a1 = new JMenuItem("Student Attendance");
        JMenuItem a2 = new JMenuItem("Teacher Attendance");
        attendance.setForeground(Color.BLUE);

        a1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon6 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon6.jpg"));
        Image image6 = icon6.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        a1.setIcon(new ImageIcon(image6));
        a1.setMnemonic('E');
        a1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, ActionEvent.CTRL_MASK));
        a1.setBackground(Color.WHITE);

        a2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon7 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon7.jpg"));
        Image image7 = icon7.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        a2.setIcon(new ImageIcon(image7));
        a2.setMnemonic('F');
        a2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_P, ActionEvent.CTRL_MASK));
        a2.setBackground(Color.WHITE);

        a1.addActionListener(this);
        a2.addActionListener(this);


        JMenu attendance_detail = new JMenu("Attendance Detail");
        JMenuItem b1 = new JMenuItem("Student Attendance Detail");
        JMenuItem b2 = new JMenuItem("Teacher Attendance Detail");
        attendance_detail.setForeground(Color.RED);

        b1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon8 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon6.jpg"));
        Image image8 = icon8.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        b1.setIcon(new ImageIcon(image8));
        b1.setMnemonic('G');
        b1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_EQUALS, ActionEvent.CTRL_MASK));
        b1.setBackground(Color.WHITE);

        b2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon9 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon7.jpg"));
        Image image9 = icon9.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        b2.setIcon(new ImageIcon(image9));
        b2.setMnemonic('H');
        b2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_L, ActionEvent.CTRL_MASK));
        b2.setBackground(Color.WHITE);

        b1.addActionListener(this);
        b2.addActionListener(this);


        JMenu exam = new JMenu("Examination");
        JMenuItem c1 = new JMenuItem("Examination Details");
        JMenuItem c2 = new JMenuItem("Enter Marks");
        exam.setForeground(Color.BLUE);

        c1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon10 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon10.png"));
        Image image10 = icon10.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        c1.setIcon(new ImageIcon(image10));
        c1.setMnemonic('I');
        c1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_PLUS, ActionEvent.CTRL_MASK));
        c1.setBackground(Color.WHITE);

        c2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon11 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon11.png"));
        Image image11 = icon11.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        c2.setIcon(new ImageIcon(image11));
        c2.setMnemonic('H');
        c2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_MINUS, ActionEvent.CTRL_MASK));
        c2.setBackground(Color.WHITE);

        c1.addActionListener(this);
        c2.addActionListener(this);


        JMenu report = new JMenu("Update Details");
        JMenuItem r1 = new JMenuItem("Update Student Detail");
        JMenuItem r2 = new JMenuItem("Update Teacher Detail");
        report.setForeground(Color.RED);

        r1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon12 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon12.png"));
        Image image12 = icon12.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        r1.setIcon(new ImageIcon(image12));
        r1.setMnemonic('J');
        r1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_6, ActionEvent.CTRL_MASK));
        r1.setBackground(Color.WHITE);

        r2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon13 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon25.png"));
        Image image13 = icon13.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        r2.setIcon(new ImageIcon(image13));
        r2.setMnemonic('K');
        r2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E, ActionEvent.CTRL_MASK));
        r2.setBackground(Color.WHITE);

        r1.addActionListener(this);
        r2.addActionListener(this);



        JMenu fee = new JMenu("Fee Details");
        JMenuItem s1 = new JMenuItem("Fee Structure");
        JMenuItem s2 = new JMenuItem("Student Fee Form");
        fee.setForeground(Color.BLUE);

        s1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon15 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon13.png"));
        Image image15 = icon15.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        s1.setIcon(new ImageIcon(image15));
        s1.setMnemonic('L');
        s1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F20, ActionEvent.CTRL_MASK));
        s1.setBackground(Color.WHITE);

        s2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon16 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon16.jpg"));
        Image image16 = icon16.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        s2.setIcon(new ImageIcon(image16));
        s2.setMnemonic('M');
        s2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F5, ActionEvent.CTRL_MASK));
        s2.setBackground(Color.WHITE);

        s1.addActionListener(this);
        s2.addActionListener(this);


        JMenu  utility = new JMenu("Utility Details");
        JMenuItem ut1 = new JMenuItem("Notepad");
        JMenuItem ut2 = new JMenuItem("Calculator");
        JMenuItem ut3 = new JMenuItem("Web Browser");
        utility.setForeground(Color.RED);

        ut1.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon18 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon18.jpg"));
        Image image18 = icon18.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        ut1.setIcon(new ImageIcon(image18));
        ut1.setMnemonic('N');
        ut1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, ActionEvent.CTRL_MASK));
        ut1.setBackground(Color.WHITE);

        ut2.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon19 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon19.png"));
        Image image19 = icon19.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        ut2.setIcon(new ImageIcon(image19));
        ut2.setMnemonic('O');
        ut2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F7, ActionEvent.CTRL_MASK));
        ut2.setBackground(Color.WHITE);

        ut3.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon20 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon20.jpg"));
        Image image20 = icon20.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        ut3.setIcon(new ImageIcon(image20));
        ut3.setMnemonic('O');
        ut3.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F8, ActionEvent.CTRL_MASK));
        ut3.setBackground(Color.WHITE);

        ut1.addActionListener(this);
        ut2.addActionListener(this);
        ut3.addActionListener(this);


        JMenu about = new JMenu("About");
        JMenuItem aboutus  = new JMenuItem("About Us");
        about.setForeground(Color.BLUE);

        aboutus.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon21 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon 21.jpg"));
        Image image21 = icon21.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        aboutus.setIcon(new ImageIcon(image21));
        aboutus.setMnemonic('P');
        aboutus.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F11, ActionEvent.CTRL_MASK));
        aboutus.setBackground(Color.WHITE);
        about.add(aboutus);
        aboutus.addActionListener(this);


        JMenu exit = new JMenu("Exit");
        JMenuItem e  = new JMenuItem("Exit");
        exit.setForeground(Color.RED);

        exit.setFont(new Font("monospaced", Font.BOLD, 16));
        ImageIcon icon22 = new ImageIcon(getClass().getResource("/university/management/system/icons/icon22.jpg"));
        Image image22 = icon22.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT);
        e.setIcon(new ImageIcon(image22));
        e.setMnemonic('P');
        e.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F12, ActionEvent.CTRL_MASK));
        e.setBackground(Color.WHITE);
        exit.add(aboutus);
        e.addActionListener(this);



        master.add(m1);
        master.add(m2);

        user.add(u1);
        user.add(u2);

        attendance.add(a1);
        attendance.add(a2);

        attendance_detail.add(b1);
        attendance_detail.add(b2);

        exam.add(c1);
        exam.add(c2);

        report.add(r1);
        report.add(r2);

        fee.add(s1);
        fee.add(s2);

        utility.add(ut1);
        utility.add(ut2);
        utility.add(ut3);

        about.add(aboutus);

        exit.add(e);



        mb.add(master);
        mb.add(user);
        mb.add(attendance);
        mb.add(attendance_detail);
        mb.add(exam);
        mb.add(report);
        mb.add(fee);
        mb.add(utility);
        mb.add(about);
        mb.add(exit);



        setJMenuBar(mb);

        setFont(new Font("Senserif", Font.BOLD, 16));
        setLayout(new FlowLayout());
        setVisible(false);
    }

   public  void actionPerformed (ActionEvent ae) {
       String msg = ae.getActionCommand();
       if (msg.equals("New Student Admission"))
       {
           new AddStudent().f.setVisible(true);

       }
       else if (msg.equals("New Faculty"))
       {
            new AddTeacher().f.setVisible(true);

       }
       else if (msg.equals("Student Details"))
       {
             new StudentDetails().setVisible(true);

       }
       else if (msg.equals("Teacher Details"))
       {
             new TeacherDetails().setVisible(true);

       }
       else if (msg.equals("Update Student Details"))
       {
             new UpdateStudent().f.setVisible(true);

       }
       else if (msg.equals("Update Teacher Details"))
       {
             new UpdateTeacher().f.setVisible(true);

       }
       else if (msg.equals("Fee Structure"))
       {
             new FeeStructure().setVisible(true);

       }
       else if (msg.equals("Student Fee Form"))
       {
             new StudentFeeForm().setVisible(true);

       }
       else if (msg.equals("Notepad"))
       {
           try
           {
               Runtime.getRuntime().exec("notepad.exe");
           } catch (Exception e) {}

       }
       else if (msg.equals("Calculator"))
       {
           try {
               Runtime.getRuntime().exec("calc.exe");
           } catch (Exception e) {}
       }
       else if (msg.equals("Web Browser"))
       {
           try {
               Runtime.getRuntime().exec("");
           } catch (Exception e) {}
       }
       else if (msg.equals("Exit"))
       {
           System.exit(0);
       }
       else if (msg.equals("About Us"))
       {
           new AboutUs().setVisible(true);
       }
       else if (msg.equals("Student Attendance"))
       {
          new StudentAttendance().setVisible(true);
       }
       else if (msg.equals("Teacher  Attendance"))
       {
                 new TeacherAttendance().setVisible(true);
       }
       else if (msg.equals("Student Attendance Detail"))
       {
                 new StudentAttendanceDetail().setVisible(true);
       }
       else if (msg.equals("Teacher Attendance Detail"))
       {
                 new TeacherAttendanceDetail().setVisible(true);
       }
       else if (msg.equals("Examination Details"))
       {
                 new ExaminationDetails().setVisible(true);
       }
       else if (msg.equals("Enter Marks"))
       {
                new EnterMarks().setVisible(true);
       }


   }
   public static void main (String args[])
    {

        new Project().setVisible(true);


    }
}
